"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""



def even_fibonacci_generator(max_number):
    sequence = []
    a = 0
    b = 1
    c = 0

    while True:
            c = a + b

            if c > max_number:
                break

            elif c % 2 == 0:
                sequence.append(c)
                a = b
                b = c

            elif c % 2 == 1:
                a = b
                b = c

            else:
                break

    print(sum(sequence))


even_fibonacci_generator(4000000)
