"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""
sequence = []
even_only = []


def fibonacci_generator(max_number):

    for num in range(1, int(max_number) + 1):

        if num < 3:
            new_num = num
        else:
            new_num = sequence[-1] + sequence[-2]
        sequence.append(new_num)

    return(sequence)


def even_number_adder():
    for num in sequence:
        if num % 2 == 0:
            if sum(even_only) + num > 4000000:
                print("Your number is too high!")
                break
            else:
                even_only.append(num)
    print(sum(even_only))


fibonacci_generator(100)
even_number_adder()
